// Code generated by mockery v2.20.2. DO NOT EDIT.

package mocks

import (
	context "context"

	model "github.com/OVantsevich/Trading-Service/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// PriceService is an autogenerated mock type for the PriceService type
type PriceService struct {
	mock.Mock
}

// GetCurrentPrices provides a mock function with given fields: ctx, names
func (_m *PriceService) GetCurrentPrices(ctx context.Context, names []string) (map[string]*model.Price, error) {
	ret := _m.Called(ctx, names)

	var r0 map[string]*model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, []string) (map[string]*model.Price, error)); ok {
		return rf(ctx, names)
	}
	if rf, ok := ret.Get(0).(func(context.Context, []string) map[string]*model.Price); ok {
		r0 = rf(ctx, names)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, []string) error); ok {
		r1 = rf(ctx, names)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetPrices provides a mock function with given fields:
func (_m *PriceService) GetPrices() ([]*model.Price, error) {
	ret := _m.Called()

	var r0 []*model.Price
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]*model.Price, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []*model.Price); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*model.Price)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateSubscription provides a mock function with given fields: names
func (_m *PriceService) UpdateSubscription(names []string) error {
	ret := _m.Called(names)

	var r0 error
	if rf, ok := ret.Get(0).(func([]string) error); ok {
		r0 = rf(names)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewPriceService interface {
	mock.TestingT
	Cleanup(func())
}

// NewPriceService creates a new instance of PriceService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewPriceService(t mockConstructorTestingTNewPriceService) *PriceService {
	mock := &PriceService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
